const $=id=>document.getElementById(id);
const SOUND_PROFILE_VERSION=3;
const legacyDefaultSounds={follow:'/assets/sounds/follow.wav',sub:'/assets/sounds/sub.wav',gift:'/assets/sounds/gift.wav',cheer:'/assets/sounds/cheer.wav',share:'/assets/sounds/share.wav',raid:'/assets/sounds/raid.wav',like:'/assets/sounds/like.wav',superchat:'/assets/sounds/superchat.wav',supersticker:'/assets/sounds/supersticker.wav',membergift:'/assets/sounds/membergift.wav'};
const defaultSounds={follow:'/assets/sounds/follow-grena.mp3',sub:'/assets/sounds/gift-bits-v2.mp3',gift:'/assets/sounds/gift-bits-v2.mp3',cheer:'/assets/sounds/gift-bits-v2.mp3',share:'/assets/sounds/share-grena.mp3',raid:'/assets/sounds/gift-bits-v2.mp3',like:'/assets/sounds/like-grena.mp3',superchat:'/assets/sounds/gift-bits-v2.mp3',supersticker:'/assets/sounds/gift-bits-v2.mp3',membergift:'/assets/sounds/gift-bits-v2.mp3'};
const soundEventNames={follow:'Follow / seguidor · TikTok',sub:'Apoyo / suscripción',gift:'Regalo / apoyo',cheer:'Bits / apoyo',share:'Compartir LIVE',raid:'Raid / apoyo',like:'100 Tap Tap · TikTok',superchat:'Super Chat / apoyo',supersticker:'Super Sticker / apoyo',membergift:'Membresías regaladas / apoyo'};
const defaults={event:'follow',name:'USUARIO_PRUEBA',message:'¡Gracias por el apoyo!',theme:'Gaming neón',accent:'#a855f7',accent2:'#22d3ee',duration:6,nameSize:30,soundEnabled:true,image:'',sound:defaultSounds.follow,soundName:'Predeterminado',animation:'pop',layers:[]};
function normalizeDesign(d={},ev=d.event||'follow'){const raw=(typeof d.sound==='string'&&d.sound.trim())?d.sound:'';const needsProfileMigration=Number(d.soundProfileVersion||0)<SOUND_PROFILE_VERSION;const wasDefault=needsProfileMigration||!raw||d.soundName==='Predeterminado'||raw===legacyDefaultSounds[ev]||raw===defaultSounds[ev]||raw==='/assets/sounds/gift-bits-grena.mp3';const sound=wasDefault?(defaultSounds[ev]||defaultSounds.follow):raw;const soundName=wasDefault?'Predeterminado':(d.soundName||'Personalizado');return {...defaults,...d,event:ev,sound,soundName,soundProfileVersion:SOUND_PROFILE_VERSION,soundEnabled:d.soundEnabled!==false};}
function newDesign(ev='follow'){return normalizeDesign({event:ev,message:eventMessages?.[ev]||'¡Gracias por el apoyo!',layers:[]},ev)}
let design=normalizeDesign(defaults,'follow'),aiImage='',selectedLayer=null,eventDesigns={},globalAlertStyle='classic';
const titles={follow:'¡NUEVO SEGUIDOR!',sub:'¡NUEVA SUSCRIPCIÓN!',gift:'¡NUEVO REGALO!',superchat:'¡SUPER CHAT!',supersticker:'¡SUPER STICKER!',cheer:'¡BITS!',share:'¡COMPARTIÓ!',like:'¡META DE LIKES!',raid:'¡RAID!',membergift:'¡MEMBRESÍAS REGALADAS!'};
const eventMessages={follow:'¡Gracias por seguirme!',sub:'¡Bienvenido al equipo!',gift:'¡Gracias por el regalo!',superchat:'¡Gracias por el apoyo!',cheer:'¡Gracias por los Bits!',share:'¡Gracias por compartir el LIVE!',like:'¡Gracias por los Tap Tap!',raid:'¡Gracias por la raid!'};
const uid=()=>Math.random().toString(36).slice(2,9);
function baseLayers(){const ev=design.event||'follow';const action=({follow:'te siguió',sub:'se suscribió',gift:'envió un regalo',cheer:'envió 500 Bits',share:'compartió el LIVE',raid:'hizo una raid'})[ev]||'apoyó el stream';return [
 {id:uid(),type:'shape',name:'Tarjeta',x:50,y:50,w:92,h:72,opacity:100,animation:'slide',variant:'simple'},
 {id:uid(),type:'shape',name:'Foto de perfil',x:17,y:50,w:18,h:58,opacity:100,animation:'pop',variant:'avatar'},
 {id:uid(),type:'text',name:'Plataforma y acción',x:58,y:31,w:62,font:14,opacity:85,animation:'slide',text:'TikTok  •  '+action},
 {id:uid(),type:'text',role:'name',name:'Usuario',x:58,y:50,w:62,font:32,opacity:100,animation:'pop',text:design.name},
 {id:uid(),type:'text',role:'message',name:'Agradecimiento',x:58,y:68,w:62,font:17,opacity:95,animation:'float',text:design.message}
]}
function ensureLayers(){if(!Array.isArray(design.layers)||!design.layers.length)design.layers=baseLayers();}
function toast(t){const el=$('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600);}
function syncCoreLayers(){ensureLayers();for(const l of design.layers){if(l.role==='title')l.text=titles[$('eventType').value];if(l.role==='name'){l.text=$('editName').value||'USUARIO_PRUEBA';l.font=Number($('nameSize').value)}if(l.role==='message')l.text=$('editMessage').value||'';if(l.name==='Personaje'&&design.image)l.src=design.image}}
function getDesign(){design={...design,event:$('eventType').value,name:$('editName').value||'USUARIO_PRUEBA',message:$('editMessage').value||'',theme:$('theme').value,accent:$('accent').value,accent2:$('accent2').value,duration:Number($('duration').value),nameSize:Number($('nameSize').value),soundEnabled:$('soundEnabled').checked,animation:$('animation')?.value||design.animation||'pop'};syncCoreLayers();return design;}
function layerNode(l){const el=document.createElement('div');el.className='free-layer '+(l.type==='text'?'layer-text':l.type==='shape'?'layer-shape':'layer-image')+' anim-'+(l.animation||'pop')+(l.variant?' shape-'+l.variant:'')+(selectedLayer===l.id?' selected':'');el.dataset.id=l.id;el.style.left=l.x+'%';el.style.top=l.y+'%';el.style.width=l.w+'%';el.style.opacity=(l.opacity??100)/100;el.style.zIndex=l.type==='shape'?1:l.type==='image'?2:3;if(l.type==='shape'){el.style.height=(l.h||35)+'%'}else if(l.type==='image'){el.style.height=(l.h||50)+'%';if(l.src)el.innerHTML=`<img src="${l.src}" alt="">`;else el.innerHTML='<div style="font-size:42px">✦</div>'}else{el.textContent=l.text||'Texto';el.style.fontSize=(l.font||28)+'px';el.style.color=l.role==='name'?'var(--accent2)':'white'};el.onpointerdown=e=>dragLayer(e,l,el);el.onclick=e=>{e.stopPropagation();selectLayer(l.id)};return el}
function renderLayers(){ensureLayers();const stage=$('alertDemo');stage.innerHTML='';stage.style.setProperty('--accent',design.accent);stage.style.setProperty('--accent2',design.accent2);design.layers.forEach(l=>stage.append(layerNode(l)));renderLayerList();}
function updateSoundUi(){const el=$('soundName');if(!el)return;const ev=design.event||$('eventType')?.value||'follow';const def=defaultSounds[ev]||defaultSounds.follow;const custom=!!design.sound&&design.sound!==def;el.textContent=custom?`Personalizado · ${design.soundName||'audio cargado'}`:`Predeterminado · ${soundEventNames[ev]||ev}`;el.classList.toggle('custom',custom)}
function updatePreview(){getDesign();$('durationValue').textContent=design.duration+' s';$('sizeValue').textContent=design.nameSize+' px';updateSoundUi();renderLayers();}
function renderLayerList(){const box=$('layerList');if(!box)return;box.innerHTML='';design.layers.slice().reverse().forEach(l=>{const r=document.createElement('div');r.className='layer-row'+(selectedLayer===l.id?' active':'');r.innerHTML=`<span>${l.type==='text'?'T':l.type==='image'?'▧':'◇'}</span><div><b>${l.name}</b><br><small>${l.animation||'pop'}</small></div><span>☰</span>`;r.onclick=()=>selectLayer(l.id);box.append(r)})}
function selectLayer(id){selectedLayer=id;const l=design.layers.find(x=>x.id===id);if(!l)return;$('layerX').value=l.x;$('layerY').value=l.y;$('layerW').value=l.w;$('layerFont').value=l.font||32;$('layerOpacity').value=l.opacity??100;$('layerAnim').value=l.animation||'pop';renderLayers()}
function editSelected(){const l=design.layers.find(x=>x.id===selectedLayer);if(!l)return;l.x=+$('layerX').value;l.y=+$('layerY').value;l.w=+$('layerW').value;l.font=+$('layerFont').value;l.opacity=+$('layerOpacity').value;l.animation=$('layerAnim').value;renderLayers()}
function dragLayer(e,l,el){e.preventDefault();selectedLayer=l.id;const box=$('alertDemo').getBoundingClientRect();const move=ev=>{l.x=Math.max(0,Math.min(100,(ev.clientX-box.left)/box.width*100));l.y=Math.max(0,Math.min(100,(ev.clientY-box.top)/box.height*100));el.style.left=l.x+'%';el.style.top=l.y+'%'};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);selectLayer(l.id)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
async function sendAlert(extra={}){const d={...getDesign(),title:titles[$('eventType').value],alertStyle:globalAlertStyle,...extra};try{const r=await fetch('/api/alert',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(d)});if(!r.ok)throw Error();toast('Alerta enviada a la superposición.')}catch{toast('No se pudo enviar. ¿Está abierto el servidor?')}}
function activatePage(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page));document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===page));const names={dashboard:'Resumen',editor:'Editor de alertas',ai:'Asistente IA',obs:'Conectar OBS'};$('pageTitle').textContent=names[page]||'GREÑA LIVE'}
document.querySelectorAll('.nav').forEach(n=>n.addEventListener('click',()=>activatePage(n.dataset.page)));
function applyAlertStyleUI(style='classic'){globalAlertStyle=['classic','option-a'].includes(style)?style:'classic';document.querySelectorAll('[data-alert-style]').forEach(card=>{const on=card.dataset.alertStyle===globalAlertStyle;card.classList.toggle('active',on);const check=card.querySelector('.style-check');if(check)check.textContent=on?'✓ Seleccionada':'Elegir'});const st=$('alertStyleStatus');if(st)st.textContent=globalAlertStyle==='option-a'?'Neón Pulse activo':'Clásica activa';}
async function loadAlertStyle(){try{const r=await fetch('/api/alert-style',{cache:'no-store'}),d=await r.json();if(r.ok)applyAlertStyleUI(d.style)}catch{applyAlertStyleUI('classic')}}
async function saveAlertStyle(style){try{const r=await fetch('/api/alert-style',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({style})}),d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo guardar');applyAlertStyleUI(d.style);toast(d.style==='option-a'?'Neón Pulse activoda para todas las alertas.':'Alertas clásicas activadas.')}catch(e){toast(e.message||'No se pudo cambiar el estilo.')}}
document.querySelectorAll('[data-alert-style]').forEach(card=>card.addEventListener('click',()=>saveAlertStyle(card.dataset.alertStyle)));
$('testClassicStyle')?.addEventListener('click',()=>sendAlert({alertStyle:'classic',platform:'TikTok',event:'gift',name:'USUARIO_PRUEBA',giftName:'Rosa',giftKind:'tiktok-gift',count:5,unitDiamonds:1,totalDiamonds:5,action:'envió Rosa × 5 · 5 diamantes'}));
$('testOptionAStyle')?.addEventListener('click',()=>sendAlert({alertStyle:'option-a',platform:'TikTok',event:'gift',name:'USUARIO_PRUEBA',giftName:'Rosa',giftKind:'tiktok-gift',count:5,unitDiamonds:1,totalDiamonds:5,action:'envió Rosa × 5 · 5 diamantes'}));
loadAlertStyle();
document.querySelectorAll('[data-event]').forEach(b=>b.addEventListener('click',()=>{const ev=b.dataset.event,platform=b.dataset.platform;$('eventType').value=ev;design=normalizeDesign(eventDesigns[ev]||{},ev);$('editMessage').value=design.message||eventMessages[ev]||'¡Gracias por el apoyo!';$('soundEnabled').checked=design.soundEnabled!==false;updatePreview();const sample={event:ev,title:titles[ev],platform,name:'USUARIO_PRUEBA',sound:design.sound,soundName:design.soundName,soundProfileVersion:SOUND_PROFILE_VERSION,soundEnabled:design.soundEnabled};if(ev==='gift'&&platform==='TikTok')Object.assign(sample,{giftName:'Rosa',giftKind:'tiktok-gift',count:5,unitDiamonds:1,totalDiamonds:5,action:'envió Rosa × 5 · 5 diamantes'});if(ev==='gift'&&platform==='Twitch')Object.assign(sample,{giftName:'Suscripciones regaladas · Tier 1',giftKind:'subscription',count:5,tier:'Tier 1',action:'regaló 5 suscripciones · Tier 1'});if(ev==='gift'&&platform==='Kick')Object.assign(sample,{giftName:'Rage Quit',giftKind:'kicks',amount:500,kickGiftTier:'MID',action:'envió Rage Quit · 500 KICKs'});if(ev==='cheer'&&platform==='Twitch')Object.assign(sample,{bits:500,giftName:'Bits',giftKind:'bits',action:'envió 500 Bits'});sendAlert(sample)}));
['eventType','editName','editMessage','theme','accent','accent2','duration','nameSize','soundEnabled','animation'].forEach(id=>$(id).addEventListener('input',updatePreview));
['layerX','layerY','layerW','layerFont','layerOpacity','layerAnim'].forEach(id=>$(id)?.addEventListener('input',editSelected));
$('addTextLayer').onclick=()=>{const l={id:uid(),type:'text',name:'Texto libre',x:50,y:25,w:50,font:28,opacity:100,animation:'pop',text:'TU TEXTO'};design.layers.push(l);selectLayer(l.id)};
$('addShapeLayer').onclick=()=>{const l={id:uid(),type:'shape',name:'Marco decorativo',x:50,y:50,w:70,h:38,opacity:100,animation:'zoom'};design.layers.unshift(l);selectLayer(l.id)};
$('addImageLayer').onclick=()=>$('extraImage').click();$('extraImage').onchange=e=>readFile(e.target.files[0],v=>{const l={id:uid(),type:'image',name:'Imagen extra',x:50,y:50,w:28,h:45,opacity:100,animation:'bounce',src:v};design.layers.push(l);selectLayer(l.id)});
$('deleteLayer').onclick=()=>{if(!selectedLayer)return;design.layers=design.layers.filter(x=>x.id!==selectedLayer);selectedLayer=null;renderLayers()};
$('character').addEventListener('change',e=>readFile(e.target.files[0],v=>{design.image=v;ensureLayers();const l=design.layers.find(x=>x.name==='Personaje');if(l)l.src=v;updatePreview()}));
$('soundFile').addEventListener('change',e=>{const file=e.target.files[0];readFile(file,v=>{design.sound=v;design.soundName=file?.name||'Audio personalizado';design.soundEnabled=true;$('soundEnabled').checked=true;updateSoundUi();toast('Sonido personalizado cargado. Guarda el diseño para conservarlo.')})});
$('testSound')?.addEventListener('click',()=>{const src=design.sound||defaultSounds[design.event]||defaultSounds.follow;if(!src)return toast('No hay sonido configurado.');const au=new Audio(src);au.volume=.8;au.play().then(()=>toast('Reproduciendo sonido.')).catch(()=>toast('El navegador bloqueó la reproducción. Pulsa otra vez.'))});
$('resetSound')?.addEventListener('click',()=>{const ev=$('eventType').value||design.event||'follow';design.sound=defaultSounds[ev]||defaultSounds.follow;design.soundName='Predeterminado';design.soundEnabled=true;$('soundEnabled').checked=true;$('soundFile').value='';updateSoundUi();toast('Sonido predeterminado restaurado. Guarda el diseño para conservarlo.')});
function readFile(file,cb){if(!file)return;if(file.size>7*1024*1024){toast('El archivo supera 7 MB.');return}const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(file)}
$('previewDesign').onclick=()=>{animatePreview();sendAlert()};$('sendToOverlay').onclick=()=>sendAlert();$('quickTest').onclick=()=>sendAlert();$('obsTest').onclick=()=>sendAlert();
$('saveDesign').onclick=async()=>{design=getDesign();eventDesigns[design.event]=JSON.parse(JSON.stringify(design));try{const r=await fetch('/api/design',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(design)});if(!r.ok)throw Error();toast('Diseño y sonido guardados para '+(eventLabels[design.event]||design.event)+'. Se usarán en eventos reales.')}catch{toast('No se pudo guardar el diseño en el servidor.')}};
// GREÑA 3.0: los diseños se cargan desde el perfil activo del servidor, no desde un localStorage compartido.
for(const [id,key] of [['eventType','event'],['editName','name'],['editMessage','message'],['theme','theme'],['accent','accent'],['accent2','accent2'],['duration','duration'],['nameSize','nameSize'],['animation','animation']])if($(id)&&design[key]!=null)$(id).value=design[key];$('soundEnabled').checked=design.soundEnabled;
$('copyOverlay').onclick=$('copyOverlay2').onclick=async()=>{try{await navigator.clipboard.writeText($('overlayUrl').textContent);toast('URL copiada.')}catch{toast('Copia manualmente la URL mostrada.')}};
function animatePreview(){const el=$('alertDemo');el.querySelectorAll('.free-layer').forEach(x=>{const c=[...x.classList].find(v=>v.startsWith('anim-'));x.classList.remove(c);void x.offsetWidth;x.classList.add(c)})}
const presets={
neon:{theme:'Gaming neón',accent:'#ec4899',accent2:'#22d3ee',animation:'pop',layout:'neon'},
royal:{theme:'Premium dorado',accent:'#f6c453',accent2:'#fff0b3',animation:'zoom',layout:'royal'},
clean:{theme:'Minimalista',accent:'#f8fafc',accent2:'#a78bfa',animation:'slide',layout:'clean'},
glitch:{theme:'Cyber glitch',accent:'#ff3158',accent2:'#22d3ee',animation:'slide',layout:'glitch'},
fiesta:{theme:'Caricatura divertida',accent:'#f43f8f',accent2:'#fbbf24',animation:'bounce',layout:'party'},
shadow:{theme:'Oscuro elegante',accent:'#8b5cf6',accent2:'#e4e4e7',animation:'float',layout:'glass'},
arcade:{theme:'Retro arcade',accent:'#f472b6',accent2:'#67e8f9',animation:'pop',layout:'arcade'},
holo:{theme:'Holográfico',accent:'#38bdf8',accent2:'#a5f3fc',animation:'float',layout:'holo'},
fire:{theme:'Impacto fuego',accent:'#f97316',accent2:'#facc15',animation:'zoom',layout:'fire'},
prism:{theme:'Gaming neón',accent:'#a855f7',accent2:'#22d3ee',animation:'zoom',layout:'prism'},
streamer:{theme:'Caricatura divertida',accent:'#fb4f9b',accent2:'#67e8f9',animation:'bounce',layout:'streamer'},
vertical:{theme:'Holográfico',accent:'#8b5cf6',accent2:'#22d3ee',animation:'slide',layout:'vertical'}
};
function presetLayers(key){const p=presets[key]||presets.neon,ev=$('eventType').value,n=$('editName').value||'USUARIO_PRUEBA',m=$('editMessage').value||eventMessages[ev]||'¡Gracias por el apoyo!';
 const shape=(name,x,y,w,h,variant,a='zoom',opacity=100)=>({id:uid(),type:'shape',name,x,y,w,h,variant,animation:a,opacity});
 const text=(role,name,x,y,w,font,a='pop',opacity=100)=>({id:uid(),type:'text',role,name,x,y,w,font,animation:a,text:role==='title'?titles[ev]:role==='name'?n:m,opacity});
 const deco=(name,txt,x,y,font,a='pop',opacity=100)=>({id:uid(),type:'text',name,x,y,w:10,font,animation:a,text:txt,opacity});
 const img=(x=25,y=50,w=28,h=55,a=p.animation)=>({id:uid(),type:'image',name:'Personaje',x,y,w,h,opacity:100,animation:a,src:design.image||''});
 if(p.layout==='royal')return [shape('Royal Glow',50,52,76,48,'royal','zoom'),shape('Línea dorada',50,52,80,52,'outline','float',75),img(27,50,29,58,'zoom'),deco('Corona','♛',48,34,28,'pop'),text('title','Título',64,39,48,17,'slide'),text('name','Usuario',64,54,50,36,'zoom'),text('message','Mensaje',64,68,50,15,'float')];
 if(p.layout==='clean')return [shape('Clean Bar',50,55,82,27,'clean','slide'),shape('Acento',18,55,2.2,27,'accent','slide'),text('title','Título',36,49,34,14,'slide',85),text('name','Usuario',59,55,47,31,'slide'),text('message','Mensaje',59,66,47,13,'float',78)];
 if(p.layout==='glitch')return [shape('Cyber Panel',50,53,82,39,'glitch','slide'),shape('Scanline',50,53,86,2,'scan','slide',90),img(27,51,27,54,'slide'),deco('Rayo','⚡',43,38,20,'pop'),text('title','Título',65,39,48,16,'slide'),text('name','Usuario',65,54,50,35,'pop'),text('message','Mensaje',65,67,50,14,'slide')];
 if(p.layout==='party')return [shape('Party Burst',50,54,73,48,'party','bounce'),deco('Estrella 1','✦',19,35,24,'bounce'),deco('Estrella 2','★',81,34,20,'pop'),deco('Confeti','✧  •  ✦',72,73,18,'float',90),img(30,51,34,63,'bounce'),text('title','Título',66,38,47,17,'bounce'),text('name','Usuario',66,54,49,35,'pop'),text('message','Mensaje',66,68,49,15,'float')];
 if(p.layout==='glass')return [shape('Glass Panel',50,54,76,41,'glass','float'),shape('Glow Edge',50,54,78,43,'outline','float',55),img(29,51,27,53,'float'),text('title','Título',63,41,49,15,'slide',75),text('name','Usuario',63,54,50,32,'float'),text('message','Mensaje',63,66,50,14,'float',80)];
 if(p.layout==='arcade')return [shape('Arcade Frame',50,52,80,46,'arcade','pop'),shape('Pixel Inner',50,52,74,39,'outline','pop',85),deco('Pixel','◆',19,34,18,'pop'),img(28,51,28,56,'pop'),text('title','Título',64,38,50,16,'pop'),text('name','Usuario',64,53,51,33,'pop'),text('message','Mensaje',64,67,51,14,'slide')];
 if(p.layout==='holo')return [shape('Holo Glass',50,52,75,45,'holo','float'),shape('Scanner',50,52,72,2,'scan','slide',80),img(30,50,29,59,'float'),deco('Holo','⌁',47,35,20,'float'),text('title','Título',64,38,48,15,'float',80),text('name','Usuario',64,53,49,34,'zoom'),text('message','Mensaje',64,66,49,14,'float')];
 if(p.layout==='fire')return [shape('Impact Frame',50,54,78,49,'fire','zoom'),deco('Chispa','✦',18,33,24,'zoom'),deco('Chispa 2','✦',83,70,17,'bounce'),img(29,51,31,61,'zoom'),text('title','Título',65,38,48,17,'zoom'),text('name','Usuario',65,54,49,36,'pop'),text('message','Mensaje',65,68,49,15,'bounce')];
 if(p.layout==='prism')return [shape('Prism Frame',50,53,78,43,'prism','zoom'),shape('Prism Inner',50,53,73,36,'outline','float',60),img(28,51,28,57,'zoom'),text('title','Título',64,39,49,16,'slide'),text('name','Usuario',64,54,50,35,'pop'),text('message','Mensaje',64,67,50,14,'float')];
 if(p.layout==='streamer')return [shape('Social Bubble',50,54,72,44,'streamer','bounce'),deco('Corazón','♥',19,35,25,'bounce'),deco('Spark','✦',81,36,21,'pop'),img(29,51,32,61,'bounce'),text('title','Título',65,39,48,16,'bounce'),text('name','Usuario',65,54,49,34,'pop'),text('message','Mensaje',65,67,49,14,'float')];
 if(p.layout==='vertical')return [shape('Vertical Card',50,53,52,58,'vertical','slide'),deco('Live','● LIVE',50,31,13,'pop'),img(35,53,23,50,'slide'),text('title','Título',61,42,30,14,'slide'),text('name','Usuario',61,54,31,27,'pop'),text('message','Mensaje',61,65,31,12,'float')];
 return [shape('Neon Frame',50,53,78,43,'neon','zoom'),shape('Light Runner',50,53,82,47,'outline','float',65),deco('Spark','✦',18,34,23,'pop'),img(28,51,29,58,'bounce'),text('title','Título',64,39,49,16,'slide'),text('name','Usuario',64,54,50,35,'pop'),text('message','Mensaje',64,67,50,14,'float')];
}
function applyPreset(key){const p=presets[key];if(!p)return;$('theme').value=p.theme;$('accent').value=p.accent;$('accent2').value=p.accent2;$('animation').value=p.animation;design.layers=presetLayers(key);selectedLayer=null;document.querySelectorAll('.template-card').forEach(x=>x.classList.toggle('active',x.dataset.preset===key));updatePreview();animatePreview();}
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>applyPreset(b.dataset.preset));
const eventLabels={follow:'Nuevo seguidor',sub:'Nueva suscripción',gift:'Regalo recibido',cheer:'Bits / apoyo',share:'Compartido',like:'100 Tap Tap / Likes',raid:'Raid'};
document.querySelectorAll('[data-alert-event]').forEach(b=>b.onclick=()=>{const current=$('eventType').value;eventDesigns[current]=JSON.parse(JSON.stringify(getDesign()));const ev=b.dataset.alertEvent;design=eventDesigns[ev]?normalizeDesign(JSON.parse(JSON.stringify(eventDesigns[ev])),ev):newDesign(ev);$('eventType').value=ev;$('editName').value=design.name||'USUARIO_PRUEBA';$('editMessage').value=design.message||eventMessages[ev]||'¡Gracias por el apoyo!';$('theme').value=design.theme||'Gaming neón';$('accent').value=design.accent||'#a855f7';$('accent2').value=design.accent2||'#22d3ee';$('duration').value=design.duration||6;$('nameSize').value=design.nameSize||30;$('animation').value=design.animation||'pop';$('soundEnabled').checked=design.soundEnabled!==false;$('editingEventLabel').textContent=eventLabels[ev]||titles[ev];document.querySelectorAll('[data-alert-event]').forEach(x=>x.classList.toggle('active',x===b));selectedLayer=null;design.layers=baseLayers();updatePreview();animatePreview()});
document.querySelectorAll('[data-control-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-control-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-control-pane]').forEach(x=>x.classList.toggle('active',x.dataset.controlPane===b.dataset.controlTab))});
$('quickPreviewBottom').onclick=()=>{animatePreview();sendAlert()};$('quickSaveBottom').onclick=()=>$('saveDesign').click();
$('openAI').onclick=()=>activatePage('ai');$('openAI2').onclick=()=>activatePage('ai');document.querySelectorAll('[data-idea]').forEach(b=>b.onclick=()=>{$('aiPrompt').value=b.dataset.idea});
$('aiImage').addEventListener('change',e=>readFile(e.target.files[0],v=>{aiImage=v;$('aiImagePreview').innerHTML=`<img src="${v}" alt="Avatar">`;toast('Avatar listo para IA.')}));
async function aiConfigured(){try{const d=await fetch('/api/ai-config',{cache:'no-store'}).then(r=>r.json());$('aiStatusText').textContent=d.configured?'✓ IA real configurada. Generará el diseño visual completo.':'IA real no configurada. Configúrala para generar diseños completos.';return !!d.configured}catch{return false}}aiConfigured();
$('configureAI').onclick=async()=>{const key=prompt('Pega tu OpenAI API key.\n\nSe guardará solo en config.local.json de este PC:','');if(key===null)return;if(!key.trim())return toast('No se guardó ninguna clave.');try{const r=await fetch('/api/ai-config',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({apiKey:key.trim()})});const d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo guardar');toast('IA configurada.');aiConfigured()}catch(e){toast(e.message)}};
$('generateConcept').onclick=async()=>{const promptText=$('aiPrompt').value.trim();if(!promptText)return toast('Describe primero la alerta que imaginas.');const btn=$('generateConcept');btn.disabled=true;btn.textContent='✧ DISEÑANDO ALERTA…';$('conceptOutput').innerHTML='<div class="empty-spark">✧</div><b>La IA está creando la composición completa…</b><p>Personaje, marco, efectos y estilo.</p>';const ev=$('aiEvent').value,animation=$('aiAnimation').value;try{const r=await fetch('/api/ai-alert',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prompt:promptText,event:ev,animation,image:aiImage,layout:$('aiLayout').value,intensity:$('aiIntensity').value,frame:$('aiFrame').checked,particles:$('aiParticles').checked})});const d=await r.json();if(!r.ok)throw Error(d.error||'IA no disponible');const c={...d.concept,image:d.image,animation,layers:d.concept?.layers||[]};$('aiModeTag').textContent='IA REAL';$('conceptOutput').innerHTML='';const wrap=document.createElement('div');wrap.className='ai-result-card';if(c.image){const img=document.createElement('img');img.src=c.image;wrap.append(img)}$('conceptOutput').append(wrap);const meta=document.createElement('div');meta.className='result-meta';meta.innerHTML=`<b>Diseño completo generado</b><br><small>${c.theme||'Estilo IA'} · editable por capas · fondo transparente</small>`;$('conceptOutput').append(meta);$('applyConcept').dataset.concept=JSON.stringify(c);$('applyConcept').disabled=false;$('testAIResult').disabled=false;toast('Diseño IA completo generado.')}catch(e){$('aiModeTag').textContent='ERROR';$('conceptOutput').innerHTML=`<div class="empty-spark">!</div><b>No se generó la alerta</b><p>${String(e.message).replace(/[<>&]/g,'')}</p>`;toast('ERROR IA: '+e.message)}finally{btn.disabled=false;btn.textContent='✧ GENERAR DISEÑO COMPLETO CON IA'}};
$('applyConcept').onclick=()=>{const c=JSON.parse($('applyConcept').dataset.concept);const cev=c.event||design.event||'follow';design=normalizeDesign({...design,...c,sound:c.sound||defaultSounds[cev]||design.sound},cev);$('eventType').value=c.event||'follow';$('theme').value=c.theme||'Gaming neón';$('editName').value=c.name||'NOMBRE_DEL_USUARIO';$('editMessage').value=c.message||eventMessages[c.event]||'¡Gracias!';$('accent').value=c.accent||'#a855f7';$('accent2').value=c.accent2||'#22d3ee';$('duration').value=c.duration||6;$('nameSize').value=c.nameSize||32;$('animation').value=c.animation||'pop';if(!design.layers?.length){design.image=c.image||'';design.layers=baseLayers()}selectedLayer=null;updatePreview();activatePage('editor');toast('Diseño IA abierto como capas editables.')};
$('testAIResult').onclick=()=>{if(!$('applyConcept').dataset.concept)return;const c=JSON.parse($('applyConcept').dataset.concept);sendAlert({...c,title:titles[c.event]})};
fetch('/api/designs',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(d.designs){eventDesigns={...eventDesigns,...d.designs};for(const [key,val] of Object.entries(eventDesigns))eventDesigns[key]=normalizeDesign(val,key);const ev=$('eventType').value;if(eventDesigns[ev]){design=normalizeDesign(eventDesigns[ev],ev);$('editName').value=design.name||'USUARIO_PRUEBA';$('editMessage').value=design.message||eventMessages[ev]||'';$('theme').value=design.theme||'Gaming neón';$('accent').value=design.accent||'#a855f7';$('accent2').value=design.accent2||'#22d3ee';$('duration').value=design.duration||6;$('nameSize').value=design.nameSize||30;$('animation').value=design.animation||'pop';$('soundEnabled').checked=design.soundEnabled!==false;updatePreview()}}}).catch(()=>{});
const wsStatus=$('serverStatus');const obsStatus=$('obsConnection');let statusSocket=null,statusRetry=null;function checkSocket(){clearTimeout(statusRetry);try{if(statusSocket&&statusSocket.readyState===WebSocket.OPEN)statusSocket.close()}catch{}const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}`);statusSocket=ws;ws.onopen=()=>{wsStatus.textContent='Servidor web conectado';obsStatus.textContent='Enlace web activo'};ws.onmessage=e=>{try{const d=JSON.parse(e.data);if((d.type==='hello'||d.type==='platform-status')&&d.status)renderPlatformStatus(d.status);if(d.type==='activity'&&d.activity)addActivity(d.activity)}catch{}};ws.onerror=()=>{wsStatus.textContent='Servidor web no disponible';obsStatus.textContent='No se detecta el servidor web';try{ws.close()}catch{}};ws.onclose=()=>{wsStatus.textContent='Reconectando servidor web…';obsStatus.textContent='Reconectando enlace local…';statusRetry=setTimeout(checkSocket,1500)}}checkSocket();design.layers=baseLayers();updatePreview();
// ===== CUENTAS CONECTADAS: TikTok + Twitch + Kick =====
const platformEls={tiktok:$('tiktokStatus')};
function renderPlatformStatus(st={}){
 for(const [p,el] of Object.entries(platformEls)){
  if(!el)continue;const x=st[p]||{};
  el.textContent=x.label||'No conectado';el.classList.toggle('ready',!!x.connected);el.classList.toggle('pending',!x.connected)
 }
 // Los tres indicadores del resumen usan la misma fuente real de /api/status.
 // (Antes TikTok/Twitch no tenían id y quedaban visualmente en "No conectado".)
}
async function refreshPlatformStatus(){try{const r=await fetch('/api/status',{cache:'no-store'}),d=await r.json();renderPlatformStatus(d.status);document.querySelectorAll('.oauth-login').forEach(b=>{const p=b.dataset.platform;b.title=d.oauthConfigured&&d.oauthConfigured[p]===false?'La conexión de esta plataforma todavía no está disponible':''})}catch{}}
async function ensurePlatformConfigured(platform){
 const st=await fetch('/api/status',{cache:'no-store'}).then(r=>r.json());
 if(st.oauthConfigured?.[platform]!==false)return true;
 const msg=st.authService?.configured?(st.authService?.lastError||'Esta plataforma todavía no está disponible.'):'El servicio de conexión todavía no está disponible.';
 toast(msg);
 return false;
}
async function loginPlatform(platform){if(!(await ensurePlatformConfigured(platform)))return;const w=640,h=780,left=Math.max(0,(screen.width-w)/2),top=Math.max(0,(screen.height-h)/2);const popup=window.open(`/oauth/${platform}/start`,'grena_oauth_'+platform,`width=${w},height=${h},left=${left},top=${top}`);if(!popup){toast('Permite ventanas emergentes para iniciar sesión.');return}toast('Completa el inicio de sesión en la ventana oficial.');const timer=setInterval(()=>{if(popup.closed){clearInterval(timer);setTimeout(refreshPlatformStatus,450)}},650)}
document.querySelectorAll('.oauth-login').forEach(b=>b.addEventListener('click',()=>loginPlatform(b.dataset.platform)));
document.querySelectorAll('.disconnect-btn').forEach(b=>b.addEventListener('click',async()=>{const p=b.dataset.platform;try{await fetch('/api/disconnect/'+p,{method:'POST'});await refreshPlatformStatus();toast('Cuenta desconectada.')}catch{toast('No se pudo desconectar.')}}));
refreshPlatformStatus();

function activityGiftVisual(a={}){const img=a.giftImage||a.imageUrl||a.giftIcon||'';if(img)return {img};const n=String(a.giftName||'').toLowerCase();if(/rosa|rose/.test(n))return {emoji:'🌹'};if(/qui[eé]reme|love|heart|coraz/.test(n))return {emoji:'💖'};if(a.event==='cheer')return {emoji:'💎'};if(a.giftKind==='subscription')return {emoji:'👑'};if(a.event==='gift')return {emoji:'🎁'};return {emoji:'⚡'}}
function activityMeta(a={}){const x=[];if(a.giftName)x.push(a.giftName);if(Number(a.count)>1)x.push(`x${Number(a.count)}`);if(Number(a.totalDiamonds)>0)x.push(`${Number(a.totalDiamonds).toLocaleString('es-DO')} diamantes`);if(Number(a.bits)>0)x.push(`${Number(a.bits).toLocaleString('es-DO')} Bits`);if(Number(a.amount)>0)x.push(`${Number(a.amount).toLocaleString('es-DO')} KICKs`);if(a.tier)x.push(String(a.tier));if(a.kickGiftTier)x.push(`Tier ${a.kickGiftTier}`);if(a.recipient)x.push(`para ${a.recipient}`);return [...new Set(x)]}
function addActivity(a){if(a?.platform&&a.platform!=='TikTok')return;const box=$('liveActivity');if(!box)return;const row=document.createElement('div');row.style.cssText='display:flex;align-items:center;gap:12px;padding:11px 12px;border:1px solid #ffffff18;border-radius:12px;background:#ffffff08';const vis=activityGiftVisual(a);const icon=document.createElement('div');icon.style.cssText='width:46px;height:46px;flex:0 0 46px;border-radius:12px;background:#ffffff0b;display:grid;place-items:center;font-size:27px;overflow:hidden';if(vis.img){const im=document.createElement('img');im.src=vis.img;im.alt=a.giftName||'regalo';im.style.cssText='width:100%;height:100%;object-fit:contain';im.onerror=()=>{icon.textContent='🎁'};icon.append(im)}else icon.textContent=vis.emoji||'⚡';const copy=document.createElement('div');copy.style.minWidth='0';const b=document.createElement('b');const label=a.event==='gift'&&a.giftName?`REGALO · ${String(a.giftName).toUpperCase()}`:(a.event==='cheer'&&a.bits?`${Number(a.bits).toLocaleString('es-DO')} BITS`:(a.eventLabel||a.title||a.event||'Evento'));b.textContent=`${a.platform||''} · ${label}`;const sm=document.createElement('small');sm.style.cssText='display:block;margin-top:3px';const detail=a.action||a.message||'realizó una acción';sm.textContent=`${a.name||'Usuario'} — ${detail}`;copy.append(b,sm);const meta=activityMeta(a);if(meta.length){const m=document.createElement('small');m.style.cssText='display:block;margin-top:5px;color:#b9c3d5';m.textContent=meta.join(' · ');copy.append(m)}row.append(icon,copy);if(box.firstElementChild?.tagName==='SMALL')box.innerHTML='';box.prepend(row);while(box.children.length>30)box.lastElementChild.remove()}
fetch('/api/activity?limit=30',{cache:'no-store'}).then(r=>r.json()).then(d=>{const box=$('liveActivity');if(box&&Array.isArray(d.activity)&&d.activity.length){box.innerHTML='';d.activity.slice().reverse().forEach(addActivity)}}).catch(()=>{});
