const $=id=>document.getElementById(id);
const state={items:[],allStats:{},platform:'',query:'',animatedOnly:false,sources:{},updatedAt:0};
const platformIcons={TikTok:'/assets/platforms/tiktok.webp',Twitch:'/assets/platforms/twitch.webp',Kick:'/assets/platforms/kick.svg',YouTube:'/assets/youtube-logo.svg'};
const kickPresetAmounts=new Set([1,10,50,100,500,1000,2000,5000,10000,50000]);
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(n){return Number(n||0).toLocaleString('es-DO')}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function sourceTime(t){if(!t)return 'Sin sincronizar';try{return new Date(t).toLocaleString('es-DO',{dateStyle:'short',timeStyle:'short'})}catch{return ''}}
function kickLocalMedia(x={}){if(x.platform!=='Kick')return '';if(x.giftKind==='subscription'||x.category==='subscription')return '/assets/kick-gifts/subscription-gift.svg';if(x.giftKind==='kicks'||String(x.unit||'').toLowerCase()==='kicks'){const n=Number(x.amount||0);return kickPresetAmounts.has(n)?`/assets/kick-gifts/kicks-${n}.svg`:'/assets/kick-gifts/kicks-generic.svg'}return '/assets/kick-gifts/kicks-generic.svg'}
function youtubeEventMedia(x={}){if(x.platform!=='YouTube')return '';const key=String(x.giftKind||x.category||'').toLowerCase().replace(/[^a-z]/g,'');return ['superchat','supersticker','membership','membershipgift','membermilestone','membershipreceived'].includes(key)?'/assets/youtube-events/'+key+'.svg':'/assets/youtube-logo.svg'}
function mediaFor(x){return x.animatedImage||x.image||youtubeEventMedia(x)||kickLocalMedia(x)||platformIcons[x.platform]||''}
function fallbackFor(x={}){if(x.platform==='TikTok')return '🎁';if(x.platform==='Twitch')return '💎';if(x.platform==='YouTube')return '▶️';if(x.platform==='Kick'&&(x.giftKind==='subscription'||x.category==='subscription'))return '🎁';return '💚'}
function card(x,i){const media=mediaFor(x),different=x.nameEs&&x.name&&x.nameEs!==x.name,fb=fallbackFor(x);return `<article class="gift-card">
  <div class="gift-media"><span class="platform-chip ${esc(x.platform)}">${esc(x.platform)}</span><div class="media-badges">${x.animatedImage?'<i class="anim">ANIMADO</i>':'<i>ESTÁTICO</i>'}${x.observed?'<i class="live">LIVE</i>':''}</div>${media?`<img loading="lazy" src="${esc(media)}" alt="${esc(x.nameEs||x.name)}" data-gift-media data-fallback="${esc(fb)}">`:`<span class="gift-fallback">${fb}</span>`}</div>
  <div class="gift-body"><h3 title="${esc(x.nameEs||x.name)}">${esc(x.nameEs||x.name)}</h3><div class="original">${different?`Original: ${esc(x.name)}`:'&nbsp;'}</div><div class="gift-value"><b>${fmt(x.amount)}</b><span>${esc(x.unit||x.category)}</span></div><div class="gift-meta">${esc(x.source||'GREÑA')}${x.region?' · '+esc(x.region):''}</div><div class="gift-actions"><button data-test-index="${i}">▶ Probar alerta</button><button data-copy-index="${i}" title="Copiar datos">{ }</button></div></div>
 </article>`}
function filtered(){const q=state.query.trim().toLowerCase();return state.items.filter(x=>(!state.platform||x.platform===state.platform)&&(!state.animatedOnly||x.animatedImage)&&(!q||[x.name,x.nameEs,x.unit,x.giftKind].some(v=>String(v||'').toLowerCase().includes(q))))}
function render(){const items=filtered();$('giftGrid').innerHTML=items.length?items.map(card).join(''):'<div class="empty-card">No hay elementos que coincidan con estos filtros.</div>';$('resultLabel').textContent=`${fmt(items.length)} resultados`;$('updatedLabel').textContent=`Última sincronización: ${sourceTime(state.updatedAt)}`;document.querySelectorAll('img[data-gift-media]').forEach(im=>im.addEventListener('error',()=>{const span=document.createElement('span');span.className='gift-fallback';span.textContent=im.dataset.fallback||'🎁';im.replaceWith(span)},{once:true}));document.querySelectorAll('[data-test-index]').forEach(b=>b.onclick=()=>testGift(items[Number(b.dataset.testIndex)]));document.querySelectorAll('[data-copy-index]').forEach(b=>b.onclick=()=>copyGift(items[Number(b.dataset.copyIndex)]));}
function renderStats(s){$('statTotal').textContent=fmt(s.total);$('statTikTok').textContent=fmt(s.tiktok);$('statTwitch').textContent=fmt(s.twitch);$('statKick').textContent=fmt(s.kick);if($('statYouTube'))$('statYouTube').textContent=fmt(s.youtube||0);$('statAnimated').textContent=fmt(s.animated)}
function renderSources(){const tt=state.sources.tiktok||{},tw=state.sources.twitch||{};const problems=[tt.error&&`TikTok: ${tt.error}`,tw.error&&`Twitch: ${tw.error}`].filter(Boolean);if(problems.length){$('sourceNote').querySelector('small').textContent=`Catálogo disponible con caché local. ${problems.join(' · ')}`}}
async function load({refresh=false}={}){const btn=$('refreshBtn');btn.disabled=true;btn.textContent=refresh?'↻ Actualizando…':'↻ Cargando…';try{const url=refresh?'/api/gift-catalog?refresh=1':'/api/gift-catalog';const d=await fetch(url,{cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error||'No se pudo cargar');return j});state.items=d.items||[];state.allStats=d.stats||{};state.sources=d.sources||{};state.updatedAt=d.updatedAt||Date.now();renderStats(state.allStats);renderSources();render();if(refresh)toast('Catálogo actualizado')}catch(e){$('giftGrid').innerHTML=`<div class="empty-card">${esc(e.message)}</div>`;toast(e.message)}finally{btn.disabled=false;btn.textContent='↻ Actualizar catálogo'}}
async function testGift(x){if(!x)return;let payload={platform:x.platform,event:'gift',name:'USUARIO_PRUEBA',giftName:x.nameEs||x.name,giftNameOriginal:x.name,giftImage:x.image||'',giftAnimatedImage:x.animatedImage||'',giftKind:x.giftKind||'gift',count:1,catalogAmount:x.amount,catalogUnit:x.unit};if(x.platform==='Twitch'&&x.giftKind==='bits')payload={...payload,event:'cheer',bits:Math.max(1,Number(x.amount)||1),giftName:'Bits'};if(x.platform==='Kick'&&x.giftKind==='kicks')payload.amount=Number(x.amount)||1;try{const r=await fetch('/api/alert',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw Error('No pude enviar la prueba');toast(`Alerta de ${x.nameEs||x.name} enviada`)}catch(e){toast(e.message)}}
async function copyGift(x){if(!x)return;try{await navigator.clipboard.writeText(JSON.stringify(x,null,2));toast('Datos copiados')}catch{toast('No pude copiar al portapapeles')}}
$('searchInput').addEventListener('input',e=>{state.query=e.target.value;render()});$('animatedOnly').addEventListener('change',e=>{state.animatedOnly=e.target.checked;render()});$('platformTabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('platformTabs').querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.platform=b.dataset.platform||'';render()});$('refreshBtn').onclick=()=>load({refresh:true});$('closeBtn').onclick=()=>{if(new URLSearchParams(location.search).get('embed')==='1')parent.postMessage({type:'grena-module-close'},location.origin);else location.href='/'};if(new URLSearchParams(location.search).get('embed')!=='1')$('closeBtn').textContent='← Centro de control';load({refresh:true});
