const $=id=>document.getElementById(id);
const state={viewers:{tiktok:0,twitch:0,kick:0},status:{},chat:[],activity:[],voiceEnabled:true};
const icons={follow:'＋',gift:'🎁',cheer:'◆',sub:'★',share:'↗',raid:'⚡',like:'♥',join:'↪'};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)}
function fmt(n){return Math.max(0,Number(n)||0).toLocaleString('es-DO')}
function time(t){return new Date(t||Date.now()).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
function renderSystem(ok){$('systemDot').classList.toggle('on',ok);$('systemText').textContent=ok?'Sistema listo':'Reconectando…'}
function renderClock(){$('clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}
setInterval(renderClock,1000);renderClock();
function renderViewers(){const v=state.viewers;$('tiktokViewers').textContent=fmt(v.tiktok);$('totalViewers').textContent=fmt(+v.tiktok||0);for(const p of ['tiktok']){const s=state.status[p]||{},on=!!(s.authenticated||s.connected||s.runtimeConnected);const el=$(p+'State');el.textContent=on?'ACTIVO':'—';el.classList.toggle('on',on)}}
function chatId(m){return m._historyId||[m.platform,m.user,m.text,m.receivedAt||m.ts||''].join('|')}
function addChat(m,history=false){if(!m||m.type!=='chat')return;const id=chatId(m);if(state.chat.some(x=>x.__id===id))return;state.chat.push({...m,__id:id,receivedAt:m.receivedAt||Date.now()});if(state.chat.length>80)state.chat.splice(0,state.chat.length-80);renderChat(history)}
function renderChat(){const box=$('chatFeed');$('chatCount').textContent=state.chat.length;if(!state.chat.length){box.innerHTML='<div class="empty">Esperando mensajes del LIVE…</div>';return}box.innerHTML=state.chat.filter(m=>String(m.platform||'tiktok').toLowerCase()==='tiktok').slice(-50).reverse().map(m=>{const p=String(m.platform||'tiktok').toLowerCase(),pc=p==='twitch'?'tw':p==='kick'?'ki':'tt',label=p==='twitch'?'TWITCH':p==='kick'?'KICK':'TIKTOK',name=m.nickname||m.user||'Usuario',initial=esc(name.trim().slice(0,1).toUpperCase()||'?');const av=m.avatar?`<img class="avatar" src="/chat/avatar?url=${encodeURIComponent(m.avatar)}" alt="" onerror="this.outerHTML='<div class=&quot;avatar fallback&quot;>${initial}</div>'">`:`<div class="avatar fallback">${initial}</div>`;return `<div class="chat-row">${av}<div class="chat-copy"><div class="chat-top"><b>${esc(name)}</b><span class="plat ${pc}">${label}</span></div><div class="chat-text">${esc(m.text||'')}</div></div><span class="time">${time(m.receivedAt)}</span></div>`}).join('')}
function activityId(a){return [a.platform,a.event,a.name,a.receivedAt].join('|')}
function addActivity(a,history=false){if(!a)return;const id=activityId(a);if(state.activity.some(x=>x.__id===id))return;state.activity.unshift({...a,__id:id});if(state.activity.length>80)state.activity.length=80;renderActivity(history)}
function renderActivity(){const box=$('activityFeed');$('eventCount').textContent=state.activity.length;if(!state.activity.length){box.innerHTML='<div class="empty">Esperando follows, regalos, shares, subs y demás eventos…</div>';return}box.innerHTML=state.activity.slice(0,60).map(a=>`<div class="event-row"><div class="event-icon">${icons[a.event]||'•'}</div><div class="event-copy"><div><b>${esc(a.name||'Usuario')}</b><span class="event-platform">${esc(a.platform||'')}</span></div><div class="event-action">${esc(a.action||a.message||'realizó una acción')}</div></div><span class="time">${time(a.receivedAt)}</span></div>`).join('')}
async function initial(){try{const [me,st,v,ac,ch]=await Promise.all([fetch('/api/account/me',{cache:'no-store'}).then(r=>r.json()),fetch('/api/status',{cache:'no-store'}).then(r=>r.json()),fetch('/api/viewers',{cache:'no-store'}).then(r=>r.json()),fetch('/api/activity?limit=60',{cache:'no-store'}).then(r=>r.json()),fetch('/chat/api/multichat-history?limit=30',{cache:'no-store'}).then(r=>r.json()).catch(()=>({messages:[]}))]);if(!me.authenticated){location.replace('/login.html');return}state.status=st.status||{};state.viewers=v.viewers||state.viewers;state.activity=[];(ac.activity||[]).slice().reverse().forEach(a=>addActivity(a,true));state.chat=[];(ch.messages||[]).forEach(m=>addChat(m,true));renderViewers();renderActivity();renderChat();renderSystem(true)}catch{renderSystem(false)}}
let wsCore,coreRetry;function core(){clearTimeout(coreRetry);try{wsCore?.close()}catch{}wsCore=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}`);wsCore.onopen=()=>renderSystem(true);wsCore.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.type==='hello'){state.status=d.status||state.status;state.viewers=d.viewers||state.viewers;renderViewers()}if(d.type==='platform-status'){state.status=d.status||state.status;renderViewers()}if(d.type==='viewers'){state.viewers=d.viewers||state.viewers;renderViewers()}if(d.type==='activity')addActivity(d.activity)}catch{}};wsCore.onclose=()=>{renderSystem(false);coreRetry=setTimeout(core,1400)};wsCore.onerror=()=>{try{wsCore.close()}catch{}}}
let wsChat,chatRetry;function chat(){clearTimeout(chatRetry);try{wsChat?.close()}catch{}wsChat=new WebSocket(`ws://${location.hostname}:8788/ws`);wsChat.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.type==='chat')addChat(d);if(d.type==='voice-control'&&typeof d.enabled==='boolean'){state.voiceEnabled=d.enabled;renderVoice()}}catch{}};wsChat.onclose=()=>{chatRetry=setTimeout(chat,1400)};wsChat.onerror=()=>{try{wsChat.close()}catch{}}}
function renderVoice(){const b=$('voiceBtn');b.classList.toggle('muted',!state.voiceEnabled);$('voiceIcon').textContent=state.voiceEnabled?'🔊':'🔇';$('voiceText').textContent=state.voiceEnabled?'Voz activa':'Voz silenciada'}
$('voiceBtn').onclick=async()=>{const next=!state.voiceEnabled;try{const r=await fetch('/chat/api/voice-control',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({enabled:next})});const d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo cambiar la voz');state.voiceEnabled=next;renderVoice();toast(next?'Chat de voz activado':'Chat de voz silenciado')}catch(e){toast(e.message||'No se pudo controlar la voz')}};
renderVoice();initial().then(()=>{core();chat()});
